### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by fatinghenji** [ProblemFactory/GenshinArtScanner#1]
Traceback (most recent call last):
  File "main.py", line 206, in <module>
  File "ocr.py", line 35, in __init__
  File "tensorflow\python\keras\saving\save.py", line 181, in load_model
  File "h5py\_hl\base.py", line 44, in is_hdf5
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 156, in h5py.h5f.is_hdf5
OSError
[5212] Failed to execute script main

**Comment by ProblemFactory** [comment]
你执行的Python脚本还是pyinstaller之后的exe？如果是脚本的话，可能是因为你环境的h5py版本太高了。如果是exe的话我上传了一个新版release，你试一下有没有解决这个问题？

**Comment by fatinghenji** [comment]
是用的exe
新版本解决了这个问题
另：背包里面所有的2星/1星全部没有识别成功，是故意为之还是程序错误？

**Comment by ProblemFactory** [comment]
没识别成功有在artifacts文件夹中生成记录嘛？可以发一份在这里吗？我这边没有一星二星的圣遗物所以没测试

**Comment by fatinghenji** [comment]
有在文件夹中记录，我打包发上来
[artifacts.zip](https://github.com/ProblemFactory/GenshinArtScanner/files/6355165/artifacts.zip)

**Comment by ProblemFactory** [comment]
定位到问题了，因为这些圣遗物没有副属性，我想当然认为圣遗物至少要有一个副属性了。已经更新代码了，你试一下新的release.

**Comment by fatinghenji** [comment]
使用了新的release，出现了新的问题。
仅仅识别了17个圣遗物就停止了。

**Comment by ProblemFactory** [comment]
停止在什么圣遗物上了，图标是什么样子的，有截图吗？还有最后点击到的圣遗物在json文件里吗？

**Comment by ProblemFactory** [comment]
最好有整个窗口的截图。

**Comment by fatinghenji** [comment]
多次尝试之后发现停下来的位置不同
最近几次识别就仅识别了第一个圣遗物
使用的是1600*900分辨率
- 程序图
![未命名1619068169](https://user-images.githubusercontent.com/37131177/115658764-02944900-a36c-11eb-81f5-810bfc0135ac.png)
- 圣遗物界面
![未命名1619068307](https://user-images.githubusercontent.com/37131177/115658923-5010b600-a36c-11eb-8922-ce76d9c14527.png)
- 识别文件
`{"version": "1", "flower": [{"setName": "gladiatorFinale", "position": "flower", "detailName": "角斗士的留恋", "mainTag": {"name": "lifeStatic", "value": 4780}, "normalTags": [{"name": "critical", "value": 0.062}, {"name": "attackPercentage", "value": 0.22699999999999998}, {"name": "lifePercentage", "value": 0.047}, {"name": "defendPercentage", "value": 0.131}], "omit": false, "id": 0, "level": 20, "star": 5}], "feather": [], "sand": [], "cup": [], "head": []}
`

**Comment by ProblemFactory** [comment]
从你这个截图看不出什么问题，我测试1600x900也是好的。这样吧，我更新一下版本，会在停止的时候打印出来停止的原因，这样更好debug一些。

**Comment by fatinghenji** [comment]
问题解决了
是腾讯的电脑管家加速的悬浮窗的问题
