### ISSUE TITLE
请求增添功能

### ISSUE THREAD

**Issue by fatinghenji** [ProblemFactory/GenshinArtScanner#2]
能否添加识别物品数量的识别？搭配这个网站使用[seelie](https://seelie.inmagi.com/)
他们支持的导入json格式如下：
`{"goals":"[{\"type\":\"character\",\"character\":\"jean\",\"current\":{\"level\":60,\"asc\":3,\"text\":\"60\"},\"goal\":{\"level\":90,\"asc\":6,\"text\":\"90\"},\"id\":1},{\"type\":\"talent\",\"character\":\"jean\",\"normal\":{\"current\":4,\"goal\":10},\"skill\":{\"current\":\"4\",\"goal\":10},\"burst\":{\"current\":\"4\",\"goal\":10},\"id\":2},{\"type\":\"weapon\",\"id\":3,\"character\":\"jean\",\"weapon\":\"prototype_rancour\",\"current\":{\"level\":60,\"asc\":3,\"text\":\"60\"},\"goal\":{\"level\":90,\"asc\":6,\"text\":\"90\"}},{\"type\":\"character\",\"character\":\"sucrose\",\"current\":{\"level\":60,\"asc\":3,\"text\":\"60\"},\"goal\":{\"level\":90,\"asc\":6,\"text\":\"90\"},\"id\":4},{\"type\":\"talent\",\"character\":\"sucrose\",\"normal\":{\"current\":1,\"goal\":\"10\"},\"skill\":{\"current\":1,\"goal\":\"10\"},\"burst\":{\"current\":\"3\",\"goal\":10},\"id\":5},{\"type\":\"weapon\",\"id\":6,\"character\":\"sucrose\",\"weapon\":\"thrilling_tales_of_dragon_slayers\",\"current\":{\"level\":20,\"asc\":0,\"text\":\"20\"},\"goal\":{\"level\":90,\"asc\":6,\"text\":\"90\"}},{\"type\":\"character\",\"character\":\"rosaria\",\"current\":{\"level\":60,\"asc\":3,\"text\":\"60\"},\"goal\":{\"level\":90,\"asc\":6,\"text\":\"90\"},\"id\":7},{\"type\":\"talent\",\"character\":\"rosaria\",\"normal\":{\"current\":\"4\",\"goal\":10},\"skill\":{\"current\":\"4\",\"goal\":10},\"burst\":{\"current\":\"4\",\"goal\":10},\"id\":8},{\"type\":\"weapon\",\"id\":9,\"character\":\"rosaria\",\"weapon\":\"dragonspine_spear\",\"current\":{\"level\":60,\"asc\":3,\"text\":\"60\"},\"goal\":{\"level\":90,\"asc\":6,\"text\":\"90\"}},{\"type\":\"character\",\"character\":\"ningguang\",\"current\":{\"level\":60,\"asc\":3,\"text\":\"60\"},\"goal\":{\"level\":90,\"asc\":6,\"text\":\"90\"},\"id\":10},{\"type\":\"talent\",\"character\":\"ningguang\",\"normal\":{\"current\":\"4\",\"goal\":10},\"skill\":{\"current\":\"4\",\"goal\":10},\"burst\":{\"current\":\"4\",\"goal\":10},\"id\":11},{\"type\":\"weapon\",\"id\":12,\"character\":\"ningguang\",\"weapon\":\"the_widsith\",\"current\":{\"level\":50,\"asc\":2,\"text\":\"50\"},\"goal\":{\"level\":90,\"asc\":6,\"text\":\"90\"}}]","inventory":"[{\"type\":\"xp\",\"item\":\"xp\",\"tier\":0,\"value\":8},{\"type\":\"mora\",\"item\":\"mora\",\"tier\":0,\"value\":254786},{\"type\":\"xp\",\"item\":\"xp_sub_1\",\"tier\":0,\"value\":15},{\"type\":\"xp\",\"item\":\"xp_sub_0\",\"tier\":0,\"value\":130},{\"type\":\"wep_xp\",\"item\":\"wep_xp\",\"tier\":0,\"value\":410},{\"type\":\"wep_xp\",\"item\":\"wep_xp_sub_1\",\"tier\":0,\"value\":22},{\"type\":\"wep_xp\",\"item\":\"wep_xp_sub_0\",\"tier\":0,\"value\":12},{\"type\":\"common\",\"item\":\"slime\",\"tier\":1,\"value\":29},{\"type\":\"common\",\"item\":\"slime\",\"tier\":0,\"value\":178},{\"type\":\"common\",\"item\":\"mask\",\"tier\":1,\"value\":23},{\"type\":\"common\",\"item\":\"mask\",\"tier\":0,\"value\":1},{\"type\":\"common\",\"item\":\"scroll\",\"tier\":1,\"value\":12},{\"type\":\"common\",\"item\":\"scroll\",\"tier\":0,\"value\":8},{\"type\":\"common\",\"item\":\"arrowhead\",\"tier\":1,\"value\":12},{\"type\":\"common\",\"item\":\"arrowhead\",\"tier\":0,\"value\":119},{\"type\":\"common_rare\",\"item\":\"horn\",\"tier\":1,\"value\":5},{\"type\":\"common_rare\",\"item\":\"horn\",\"tier\":0,\"value\":119},{\"type\":\"common_rare\",\"item\":\"ley_line\",\"tier\":1,\"value\":16},{\"type\":\"common_rare\",\"item\":\"ley_line\",\"tier\":0,\"value\":10},{\"type\":\"common_rare\",\"item\":\"chaos\",\"tier\":1,\"value\":5},{\"type\":\"common_rare\",\"item\":\"chaos\",\"tier\":0,\"value\":64},{\"type\":\"common_rare\",\"item\":\"mist\",\"tier\":0,\"value\":0},{\"type\":\"common_rare\",\"item\":\"sacrificial_knife\",\"tier\":1,\"value\":1},{\"type\":\"common_rare\",\"item\":\"sacrificial_knife\",\"tier\":0,\"value\":28},{\"type\":\"common\",\"item\":\"f_insignia\",\"tier\":1,\"value\":14},{\"type\":\"common\",\"item\":\"f_insignia\",\"tier\":0,\"value\":2},{\"type\":\"common\",\"item\":\"th_insignia\",\"tier\":1,\"value\":2},{\"type\":\"common\",\"item\":\"th_insignia\",\"tier\":0,\"value\":60},{\"type\":\"element_2\",\"item\":\"hurricane_seed\",\"tier\":0,\"value\":1},{\"type\":\"element_2\",\"item\":\"lightning_prism\",\"tier\":0,\"value\":2},{\"type\":\"element_2\",\"item\":\"basalt_pillar\",\"tier\":0,\"value\":1},{\"type\":\"element_2\",\"item\":\"hoarfrost_core\",\"tier\":0,\"value\":6},{\"type\":\"element_2\",\"item\":\"cleansing_heart\",\"tier\":0,\"value\":1},{\"type\":\"element_2\",\"item\":\"juvenile_jade\",\"tier\":0,\"value\":2},{\"type\":\"common\",\"item\":\"nectar\",\"tier\":1,\"value\":14},{\"type\":\"common\",\"item\":\"nectar\",\"tier\":0,\"value\":13},{\"type\":\"element_1\",\"item\":\"brilliant_diamond\",\"tier\":1,\"value\":6},{\"type\":\"common_rare\",\"item\":\"bone_shard\",\"tier\":0,\"value\":14},{\"type\":\"element_1\",\"item\":\"agnidus_agate\",\"tier\":0,\"value\":24},{\"type\":\"element_1\",\"item\":\"varunada_lazurite\",\"tier\":1,\"value\":10},{\"type\":\"element_1\",\"item\":\"varunada_lazurite\",\"tier\":0,\"value\":21},{\"type\":\"element_1\",\"item\":\"vajrada_amethyst\",\"tier\":1,\"value\":4},{\"type\":\"element_1\",\"item\":\"vajrada_amethyst\",\"tier\":0,\"value\":24},{\"type\":\"element_1\",\"item\":\"vayuda_turqoise\",\"tier\":0,\"value\":5},{\"type\":\"element_1\",\"item\":\"shivada_jade\",\"tier\":1,\"value\":12},{\"type\":\"element_1\",\"item\":\"shivada_jade\",\"tier\":0,\"value\":2},{\"type\":\"element_1\",\"item\":\"prithiva_topaz\",\"tier\":1,\"value\":9},{\"type\":\"element_1\",\"item\":\"prithiva_topaz\",\"tier\":0,\"value\":1},{\"type\":\"talent\",\"item\":\"freedom\",\"tier\":1,\"value\":24},{\"type\":\"talent\",\"item\":\"freedom\",\"tier\":0,\"value\":6},{\"type\":\"talent\",\"item\":\"resistance\",\"tier\":1,\"value\":4},{\"type\":\"talent\",\"item\":\"ballad\",\"tier\":0,\"value\":1},{\"type\":\"talent\",\"item\":\"prosperity\",\"tier\":0,\"value\":2},{\"type\":\"talent\",\"item\":\"diligence\",\"tier\":1,\"value\":6},{\"type\":\"talent\",\"item\":\"diligence\",\"tier\":0,\"value\":27},{\"type\":\"talent\",\"item\":\"gold\",\"tier\":1,\"value\":6},{\"type\":\"talent\",\"item\":\"gold\",\"tier\":0,\"value\":22},{\"type\":\"wam\",\"item\":\"decarabian\",\"tier\":0,\"value\":3},{\"type\":\"wam\",\"item\":\"boreal_wolf\",\"tier\":1,\"value\":2},{\"type\":\"wam\",\"item\":\"boreal_wolf\",\"tier\":0,\"value\":1},{\"type\":\"wam\",\"item\":\"dandelion_gladiator\",\"tier\":0,\"value\":3},{\"type\":\"wam\",\"item\":\"guyun\",\"tier\":0,\"value\":1},{\"type\":\"wam\",\"item\":\"mist_veiled_elixer\",\"tier\":2,\"value\":1},{\"type\":\"wam\",\"item\":\"mist_veiled_elixer\",\"tier\":1,\"value\":1},{\"type\":\"wam\",\"item\":\"mist_veiled_elixer\",\"tier\":0,\"value\":12},{\"type\":\"wam\",\"item\":\"aerosiderite\",\"tier\":0,\"value\":1},{\"type\":\"local\",\"item\":\"calla_lily\",\"tier\":0,\"value\":42},{\"type\":\"local\",\"item\":\"wolfhook\",\"tier\":0,\"value\":30},{\"type\":\"local\",\"item\":\"valberry\",\"tier\":0,\"value\":31},{\"type\":\"local\",\"item\":\"cecilia\",\"tier\":0,\"value\":44},{\"type\":\"local\",\"item\":\"windwheel_aster\",\"tier\":0,\"value\":11},{\"type\":\"local\",\"item\":\"jueyun_chili\",\"tier\":0,\"value\":18},{\"type\":\"local\",\"item\":\"noctilucous_jade\",\"tier\":0,\"value\":23},{\"type\":\"local\",\"item\":\"silk_flower\",\"tier\":0,\"value\":27},{\"type\":\"local\",\"item\":\"glaze_lilly\",\"tier\":0,\"value\":6},{\"type\":\"local\",\"item\":\"qingxin\",\"tier\":0,\"value\":27},{\"type\":\"local\",\"item\":\"starconch\",\"tier\":0,\"value\":25},{\"type\":\"local\",\"item\":\"violetgrass\",\"tier\":0,\"value\":10},{\"type\":\"local\",\"item\":\"small_lamp_grass\",\"tier\":0,\"value\":73},{\"type\":\"local\",\"item\":\"dandelion_seed\",\"tier\":0,\"value\":32},{\"type\":\"local\",\"item\":\"cor_lapis\",\"tier\":0,\"value\":29},{\"type\":\"common\",\"item\":\"scroll\",\"tier\":2,\"value\":12},{\"type\":\"common_rare\",\"item\":\"mist\",\"tier\":1,\"value\":23},{\"type\":\"talent\",\"item\":\"ballad\",\"tier\":1,\"value\":12},{\"type\":\"talent\",\"item\":\"prosperity\",\"tier\":1,\"value\":5}]","inactive":"{}","tasks":null}`

**Comment by ProblemFactory** [comment]
好的我研究一下，不过这个增加的需要识别的字符量比较多，可能会降低OCR的准确率。

**Comment by fatinghenji** [comment]
请问有进展了吗

**Comment by ProblemFactory** [comment]
目前在考虑重新实现一套图标识别+文字识别的方案，这样可以批量处理一页的物品，避免点来点去浪费时间，不过这样可能要重新做一个模型，窗口内元素坐标的计算也有点麻烦。目前优先处理新圣遗物和完善圣遗物扫描功能，然后我准备再做一个独立的模块来识别物品。

**Comment by fatinghenji** [comment]
辛苦啦

**Comment by fatinghenji** [comment]
请问有进展吗？
